CikolataWebSitesi/Controllers/PromOnayController.cs
using CikolataWebSitesi.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;


namespace CikolataWebSitesi.Controllers
{
    public class PromOnayController : Controller
    {
        
        private cikolataEntities db = new cikolataEntities();

        // GET: PromOnay
        public ActionResult Index()
        {
            var tblPromOnay = db.tblPromOnay.Include(t => t.tblKullanici).Include(t => t.tblPromosyon).Include(t => t.tblUrun);
            return View(tblPromOnay.ToList());
        }
        public ActionResult Onay(int str)
        {
            
                tblPromOnay promOnay = db.tblPromOnay.Find(str);
                tblFiyat fiyat = db.tblFiyat.Find(promOnay.tblUrun.fiyatID);
                fiyat.urunPromosyonID = promOnay.PromosyonId;
                fiyat.satisFiyati = fiyat.satisFiyati - ((fiyat.satisFiyati * promOnay.tblPromosyon.promosyonIndirimOrani) / 100);
                db.Entry(fiyat).State = EntityState.Modified;
                promOnay.onayDurumu = true;
                db.Entry(promOnay).State = EntityState.Modified;
                db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CikolataWebSitesi/Views/PromOnay/Index.cshtml
@model IEnumerable<CikolataWebSitesi.Models.tblPromOnay>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_SaticiLayout.cshtml";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.onayDurumu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.satisFiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tblKullanici.kullaniciAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tblPromosyon.promosyonAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tblUrun.urunAd)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var id = 12;
        if (id == 12)
        {
            <tr>
                @if (item.onayDurumu == false || item.onayDurumu == null)
                {
                    <td>
                        @Html.ActionLink("Onayla", "Onay", "PromOnay", new { str = item.onayID }, new { @class = "delete" })
                    </td>
                }
                else if (item.onayDurumu == true)
                {
                    <td>
                        <label class="label label-success">ONAYLANDI</label>
                    </td>
                }

                <td>
                    @Html.DisplayFor(modelItem => item.satisFiyat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblKullanici.kullaniciAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblPromosyon.promosyonAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblUrun.urunAd)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.onayID })
                </td>

            </tr>
        }
        else
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.onayDurumu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.satisFiyat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblKullanici.kullaniciAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblPromosyon.promosyonAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblUrun.urunAd)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.onayID })
                </td>

            </tr>
        }

    }

</table>